# Generated by Django 3.1.4 on 2020-12-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isTaken',
            field=models.BooleanField(default=False),
        ),
    ]
