# Generated by Django 3.1.4 on 2020-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
