# Generated by Django 3.1.4 on 2020-12-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='isPaid',
        ),
    ]
