# Generated by Django 3.1.4 on 2020-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_auto_20201222_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_slug',
            field=models.SlugField(blank=True),
        ),
    ]
