# Generated by Django 3.1.4 on 2020-12-23 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_auto_20201222_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='time_taken',
            field=models.TimeField(default=datetime.datetime(2020, 12, 23, 8, 4, 37, 472425, tzinfo=utc)),
        ),
    ]
