# Generated by Django 3.1.4 on 2020-12-23 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_response_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='response',
            name='time_taken',
            field=models.TimeField(default=datetime.datetime(2020, 12, 23, 9, 8, 50, 540855, tzinfo=utc)),
        ),
    ]
