# Generated by Django 3.1.4 on 2020-12-23 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0013_auto_20201223_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='time_taken',
            field=models.TimeField(default=datetime.datetime(2020, 12, 23, 9, 15, 30, 491095, tzinfo=utc)),
        ),
    ]
