# Generated by Django 3.1.4 on 2020-12-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_auto_20201223_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='time_taken',
            field=models.TimeField(blank=True),
        ),
    ]
