# Generated by Django 3.1.4 on 2020-12-23 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0016_auto_20201223_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='time_taken',
            field=models.TimeField(verbose_name=datetime.datetime(2020, 12, 23, 10, 40, 27, 103557, tzinfo=utc)),
        ),
    ]
