# Generated by Django 3.1.4 on 2020-12-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0018_auto_20201223_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('text', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='free_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
