# Generated by Django 3.1.4 on 2020-12-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0019_auto_20201223_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='winning_amoun',
            field=models.IntegerField(default=0),
        ),
    ]
