# Generated by Django 3.1.4 on 2020-12-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0020_quiz_winning_amoun'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_score_point',
            field=models.IntegerField(default=50),
        ),
    ]
