# Generated by Django 3.1.4 on 2020-12-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0021_quiz_quiz_score_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_negative_point',
            field=models.IntegerField(default=50),
        ),
    ]
