# Generated by Django 3.1.4 on 2020-12-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0023_auto_20201226_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
    ]
