# Generated by Django 3.1.4 on 2020-12-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0024_remove_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_negative_point',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_score_point',
            field=models.FloatField(default=50),
        ),
    ]
